modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "cloud_forest"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:dirt"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = ""
displayURL = ""
displayName = "cloud_forest"
description = '''
    Template Desc.
    '''

[[dependencies.cloud_forest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cloud_forest]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cloud_forest]]
modId = "blueprint"
mandatory = true
versionRange = "[7.1.0,)"
ordering = "AFTER"
side = "BOTH"